export const productos = [
  {
    id: 1,
    title: "Andriod 12.0",
    price: 2096,
    stock: 4,
    description: "Última versión de esta marca",
    category: "tablets",
    img: "https://i.imgur.com/q8cttNS.jpg",
  },
  {
    id: 2,
    title: "Android 11.0",
    price: 3498,
    stock: 5,
    description: "Esta versión cuenta con un mini-teclado de regalo",
    category: "tablets",
    img: "https://i.imgur.com/R02MRZj.jpg",
  },
  {
    id: 3,
    title: "Samsung Galaxy 14.5G",
    price: 12700,
    stock: 1,
    description: "Última oferta de esta marca",
    category: "celulares",
    img: "https://i.imgur.com/x6ASYcj.jpg",
  },
  {
    id: 4,
    title: "Xiaomi 11.0",
    price: 17800,
    stock: 0,
    description:
      "Este es el que más se vende, este atente a la próxima partida",
    category: "celulares",
    img: "https://i.imgur.com/UyHUVMz.jpg",
  },
  {
    id: 5,
    title: "Asus Gamming 15.6",
    price: 21500,
    stock: 13,
    description:
      "Es la mejor y más adecuada para quienes les gustan los videojuegos en tiempo real",
    category: "pc",
    img: "https://i.imgur.com/sxJsLvP.jpg",
  },
  {
    id: 6,
    title: "intel Gammer Pro",
    price: 21255,
    stock: 14,
    description: "La torre más adecuada para los videojuegos interactivos",
    category: "pc",
    img: "https://i.imgur.com/KmWj3Xj.jpg",
  },
];
